luarpmsort: add -r option
This allows us to use luarpmsort like the legacy rpmsort program.
Also, set RPMSORT variable once in all scripts that use it.

diff --git a/luarpmsort b/luarpmsort
--- a/luarpmsort
+++ b/luarpmsort
@@ -1,6 +1,6 @@
 #!/bin/bash
-# Note: Unlike the old rpmsort, newer versions are at the top!
 rpmsort() {
+        direction=$1
 	script='
 function parse(ver)
 	local epoch, version, release = 0, ver, 0
@@ -29,17 +29,38 @@ function pkgvercmp(a, b)
 	if vcmp ~= 0 then return vcmp end
 
 	return rpm.vercmp(ar, br)
-end	
+end
 
 vers = {}
 for line in io.stdin:lines() do
 	table.insert(vers, line)
 end
-table.sort(vers, function(a, b) return pkgvercmp(a, b) == 1 end)
+table.sort(vers, function(a, b) return pkgvercmp(a, b) == '"$direction"' end)
 print(table.concat(vers, "\n"))
 '
 
 	rpm --eval "%{lua: ${script}}"
 }
 
-rpmsort
+usage() {
+    cat >&2 <<EOF
+$0 - sort standard input according to rpm version sorting conventions,
+     using rpm's built-in lua interpreter
+Options:
+	-r|--reverse	sort backwards
+	-h|--help	print this help
+EOF
+    exit 0
+}
+
+DIRECTION=-1
+while [[ $# -gt 0 ]]; do
+    case $1 in
+	-r|--reverse) DIRECTION=1;;
+	-h|--help) usage;;
+	*)  echo "$0: invalid parameter $1 ignored" >&2;;
+    esac
+    shift
+done
+
+rpmsort "$DIRECTION"
