Find update candiate links across all module subdirectories
If module subdirectories are versioned, we need to search a bit harder
for potential update candiates as the name of the module subdirectory
differs.
We therefore search all weak-updates subdirectories of the $krel kernel
for a module module matching the same name (taking into accout different
compressions).
Should we find multiple modules that match (which should not happen!)
we flag this but continue regardless. This way, the first element in
the list will be taken as the potential update candidate.

Signed-off-by: Egbert Eich <eich@suse.com>

diff --git a/weak-modules2 b/weak-modules2
--- a/weak-modules2
+++ b/weak-modules2
@@ -336,13 +336,23 @@ find_kmps() {
     dlog "find_kmps: kmps found: " $(cat $tmpdir/kmps)
 }
 
+other_symlinks() {
+    local module=$1 krel=$2 file
+    filename=${module#/lib/modules/*/updates/*/}
+    find /lib/modules/$krel/weak-updates/*/ -name "${filename%.ko*}.ko*" -printf "%p "
+}
+
 __previous_version_of_kmp() {
     local new_kmp=$1 krel=$2
     local module symlink old_kmp
     
     while read module; do
 	symlink=$(symlink_to_module $module $krel)
-	[ -e "$symlink" ] || continue
+	[ -e "$symlink" ] || {
+	    symlink=($(other_symlinks $module $krel))
+	    [ ${#symlink[*]} -gt 0 ] || continue
+	    [ ${#symlink[*]} -eq 1 ] || { echo "Error: Module ${module##*/} exists more than once for kernel $krel!"; }
+	}
 	[ -L "$symlink" ] || return
 
 	old_kmp=$(grep -l "$(readlink "$symlink")" $tmpdir/modules-* | sed 's:.*/modules-::' ) || return
