weak-modules2: obtain list of initrd modules from dracut (jsc#PED-1915)
After previous patch we ignore INITRD_MODULES. That means that we will
obtain the list of modules to include from the current initrd. But that
might not be enough if new modules are to be added. We should read the
dracut configuration, which is supposed to replace INITRD_MODULES.

Obtain the list of dracut configuration files (code copied from dracut 059)
and parse the content to obtain the values of the variables that affect
the list of modules ("drivers" in dracut nomenclature) to be included.
This is not exactly like dracut's logic because we don't have the module
autodetection. But it comes close, in particular if we add in the
modules from the existing initrd. In practice, what matters most is that
we understand "add_drivers+=" directives that 3rd party module authors
may put into the dracut configuration.

This code executes "arbitrary" scripts as root with bash, which is insecure.
dracut does this, too, so this doesn't pose additional danger to the
system. However, in wm2 we can source these scripts with reduced privileges,
because we just need to set some variables.

Signed-off-by: Martin Wilck <mwilck@suse.com>

diff --git a/weak-modules2 b/weak-modules2
--- a/weak-modules2
+++ b/weak-modules2
@@ -390,10 +390,70 @@ previous_version_of_kmp() {
     return $res
 }
 
-get_initrd_basenames() {
-    $LSINITRD /boot/initrd-$1 | \
-	sed -rn 's:.*\<usr/lib/modules/.*/::p' | \
+# Create list of dracut configuration files to read, taking into
+# account priorities of the user and built-in configuration.
+# Copied from dracut.sh as of dracut 059 (GPL-2.0-or-later)
+dropindirs_sort() {
+    local suffix=$1
+    shift
+    local -a files
+    local f d
+
+    for d in "$@"; do
+        for i in "$d/"*"$suffix"; do
+            if [[ -e $i ]]; then
+                printf "%s\n" "${i##*/}"
+            fi
+        done
+    done | sort -Vu | {
+        readarray -t files
+
+        for f in "${files[@]}"; do
+            for d in "$@"; do
+                if [[ -e "$d/$f" ]]; then
+                    printf "%s\n" "$d/$f"
+                    continue 2
+                fi
+            done
+        done
+    }
+}
+
+get_current_basenames() {
+    $LSINITRD /boot/initrd-$1 |
+	sed -rn 's:.*\<usr/lib/modules/.*/::p' |
 	strip_mod_extensions
+}
+
+DRACUT_CONFFILE=/etc/dracut.conf
+DRACUT_CONFDIR=/etc/dracut.conf.d
+DRACUT_BUILTIN_CONFDIR=/usr/lib/dracut/dracut.conf.d
+GET_DRACUT_DRIVERS=/usr/lib/module-init-tools/get_dracut_drivers
+
+get_initrd_basenames() {
+    local setpriv=$(command -v setpriv)
+    local conf= cf
+
+    [[ -x "$GET_DRACUT_DRIVERS" && "$setpriv" ]] || {
+	echo "$0: unable to parse dracut configuration, skipping it" >&2
+	get_current_basenames "$1"
+	return
+    }
+
+    [[ ! -f "$DRACUT_CONFFILE" ]] ||
+	conf="$(cat "$DRACUT_CONFFILE")"
+
+    # Assemble the content of the dracut configuration files.
+    # Make sure to put a newline between subsequent conf file contents.
+    for cf in $(dropindirs_sort .conf "$DRACUT_CONFDIR" "$DRACUT_BUILTIN_CONFDIR"); do
+	conf="$conf
+$(cat "$cf")"
+    done
+
+    # run get_dracut_drivers with reduced privileges
+    get_current_basenames "$1" |
+	"$setpriv" --reuid=nobody --regid=nobody --clear-groups --inh-caps=-all \
+		   "$GET_DRACUT_DRIVERS" "$conf"
 }
 
 # test if rebuilding initrd is needed for $krel.
