wm2: Do not split messages across multiple lines
It's not possible to find the split message with grep and similar tools

diff --git a/weak-modules2 b/weak-modules2
--- a/weak-modules2
+++ b/weak-modules2
@@ -338,8 +338,7 @@ check_kmp() {
 		 $tmpdir/modules-$kmp \
 	     | sort -u)
     if [ $# -ne 1 ]; then
-	echo "Error: package $kmp seems to contain modules for multiple" \
-	     "kernel versions" >&2
+	echo "Error: package $kmp seems to contain modules for multiple kernel versions" >&2
 	return 1
     fi
     echo $1 > $tmpdir/krel-$kmp
@@ -348,8 +347,7 @@ check_kmp() {
     # Make sure none of the modules are in kernel/ or weak-updates/
     if grep -qE -e '^/usr/lib/modules/[^/]+/(kernel|weak-updates)/' \
 	    $tmpdir/modules-$kmp; then
-	echo "Error: package $kmp must not install modules into " \
-	     "kernel/ or weak-updates/" >&2
+	echo "Error: package $kmp must not install modules into kernel/ or weak-updates/" >&2
 	return 1
     fi
     sed -e 's:.*/::' $tmpdir/modules-$kmp \
