weak-modules2: skip "test" call to has_unresolved_symbols
The first call is supposed to check whether the kernel at hand
is in an inconsistent state before adding the KMP. But this is
a very rare situation; has_unresolved_symbols() is a slow operation (calling
depmod) and should thus not be called without good reason.

If adding the kmp failed and OPT_DEBUG=1, we carry out this operation
to provide a clue to users.

diff --git a/weak-modules2 b/weak-modules2
--- a/weak-modules2
+++ b/weak-modules2
@@ -595,10 +595,6 @@ add_kmp() {
 	[ -d $dir ] || continue
 	system_map=$(find_usrmerge_boot System.map "$krel")
 	[ -n "$system_map" ] || continue
-	if opt_debug=1 has_unresolved_symbols "$krel" "/"; then
-	    echo "Warning: /lib/modules/$krel is inconsistent" >&2
-	    echo "Warning: weak-updates symlinks might not be created" >&2
-	fi
 
 	if kmp_is_present $kmp $krel; then
 	    log "Package $kmp does not need to be added to kernel $krel"
@@ -619,8 +615,14 @@ add_kmp() {
 		cat $tmpdir/basenames-{$old_kmp,$kmp} \
 		| run_depmod_build_initrd "$krel" || status=1
 	    fi
+	elif [[ $old_kmp ]]; then
+	    log "Package $old_kmp kept in kernel $krel (not replaced by $kmp)"
 	else
-	    dlog "add_kmp: skipped $kmp"
+	    echo "FAILED to add $kmp in kernel $krel" >&2
+	    if [[ $opt_debug -gt 0 ]] && \
+		   has_unresolved_symbols "$krel" "/"; then
+		echo "Warning: /lib/modules/$krel is inconsistent" >&2
+	    fi
 	fi
     done
     dlog "add_kmp: status=$status"
