change for better maintainability
the compound statement is always going to have 0 as an exit status instead of
only if the directory exists

diff --git a/kernel-scriptlets/cert-script b/kernel-scriptlets/cert-script
--- a/kernel-scriptlets/cert-script
+++ b/kernel-scriptlets/cert-script
@@ -73,7 +73,7 @@ case $op in
 		fi
 	    done
 	else
-	    test -d /sys/firmware/efi/efivars && echo "WARNING: cannot update MOK variables since /sys/firmware/efi/efivars is not writeable" 1>&2
+	    test ! -d /sys/firmware/efi/efivars || echo "WARNING: cannot update MOK variables since /sys/firmware/efi/efivars is not writeable" 1>&2
 	fi
 	;;
     preun)
