rpm-script: create dangling symlinks in kiwi environments
In image build environments such as kiwi (more precisely, if /.buildenv
exists), dracut is not invoked by weak-modules2. That means that the logic
of 19c92c5 ("rpm-script: fix handling of /boot/vmlinuz and /boot/initrd"),
which tries to avoid creating dangling symlinks, doesn't work.

While this should eventually be fixed in kiwi, we can't wait for that to happen.
In such cases, fall back to creating a dangling symlink, hoping that kiwi will
run dracut later, creating the symlink's target.

Fixes: 19c92c5 ("rpm-script: fix handling of /boot/vmlinuz and /boot/initrd")
Signed-off-by: Martin Wilck <mwilck@suse.com>

diff --git a/kernel-scriptlets/rpm-script b/kernel-scriptlets/rpm-script
--- a/kernel-scriptlets/rpm-script
+++ b/kernel-scriptlets/rpm-script
@@ -123,8 +123,8 @@ create_boot_symlinks() {
     for x in /boot/"$image" /boot/initrd; do
 	[ -f "$x-$rel_flav" ] || broken=yes
     done
-    if [ "$broken" ]; then
-        echo "ERROR: cannot create symlinks /boot/$image and /boot/initrd" >&2
+    if [ "$broken" ] && [ ! -e /.buildenv ]; then
+	echo "ERROR: cannot create symlinks /boot/$image and /boot/initrd" >&2
     else
 	for x in /boot/"$image" /boot/initrd; do
 	    rm -f "$x"
